### ISSUE TITLE
[BUG] Value property of Input component not actually bindable

### ISSUE THREAD

**Issue by Wombosvideo** [kampsy/ui#12]
## Quick Glance

- The `value` property of `Input` is bindable but it doesn't react to changes

## Description

```svelte
<script>
  import { Input } from 'kampsy-ui';

  let value = $state('initial value');
</script>

<Input bind:value />

<p>
  You typed {value}.
</p>
```

- Input correctly applies initial value
- Typing text doesn't update the paragraph text

## Proposition

Change `{value}` to `bind:value` in `src/lib/input/input.svelte`.

**Comment by kampsy** [comment]
Thanks for the report. The fix for this issue is in the dev pr https://github.com/kampsy/ui/pull/9, and it applies to the textarea component. I'm just cleaning up the text component.

**Comment by Wombosvideo** [comment]
Great, looking forward to see it

**Comment by Wombosvideo** [comment]
This issue is still present as of version 0.1.2
