### ISSUE TITLE
Add GitHub Actions pipeline for npm releases

### ISSUE THREAD

**Issue by Wombosvideo** [kampsy/ui#15]
## Quick Glance

- Add GitHub Actions pipeline for npm releases

## Description

I saw that the npm packages were out of date and not reflecting the same state as the documentation website. I suggest adding a GitHub Actions pipeline to automate npm releases.

## Why this is important

Keeping track of changes and manually updating npm releases can be a hassle and easily repeat situations of out-of-date packages. Additionally, the release version should always match the feature set and code samples in the documentation.

## Original Issue Content

You mentioned certain fixes and new features but the NPM package version hasn't changed since before that. Do you need help integrating NPM releases to GitHub Actions?

**Comment by kampsy** [comment]
Hello @Wombosvideo,

Yes, I could definitely use some help setting up the NPM release with GitHub Actions!

I really appreciate any help you can provide.

**Comment by Wombosvideo** [comment]
I will look into this as soon as I can. I have _some_ experience with GitHub Actions but I'd need to experiment a little first. I'll open a PR as soon as I am either confident that it works, or if it needs review (that would be a draft PR then).

**Comment by Wombosvideo** [comment]
In terms of Releases, [semantic-release](https://github.com/semantic-release/semantic-release) is probably the easiest solution. And it seems like they've [made it easy](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/plugins.md#default-plugins) to use it for npm package releases as well.

Since you're already using [the right commit message format](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format) it should be a lot easier to implement.

**Comment by kampsy** [comment]
Awesome, looking forward to it! My experience with GitHub Actions has mostly been around deployments, running linting, Vite tests, and Playwright, but not NPM package releases. Excited to see your PR!
