### ISSUE TITLE
Value property of Input component still not actually bindable

### ISSUE THREAD

**Issue by Wombosvideo** [kampsy/ui#16]
## Quick Glance

- The `value` property of `Input` is bindable but it doesn't react to changes

## Description

I just upgraded to `kampsy-ui@0.1.2` and #12 is still present. I was not able to reopen the issue, so I've created a new one.

```svelte
<script>
  import { Input } from 'kampsy-ui';

  let value = $state('initial value');
</script>

<Input bind:value />

<p>
  You typed {value}.
</p>
```

- Input correctly applies initial value
- Typing text doesn't update the paragraph text

## Proposition

Change `{value}` to `bind:value` in `src/lib/input/input.svelte`.

**Comment by kampsy** [comment]
Oopsie I will fix this minor issue and let you focus on the GitHub action

**Comment by kampsy** [comment]
Fixed!
https://github.com/user-attachments/assets/8424f33a-7a44-4aa0-bfdf-cb3adb9a8e87
