### ISSUE TITLE
Use `<label>` for Input component label

### ISSUE THREAD

**Issue by Wombosvideo** [kampsy/ui#17]
## Quick Glance

- Use `<label>` for the label of the `Input` component
- Improves accessibility and user experience

## Description

Using an `Input` with a `label` gives a labelled input box. So far so good. To improve the user experience, the label should be clickable. When clicked, the `<input>` element should be focused.

## Proposition

Modify the `Input` component to use a `<label>` element, with a `for` attribute bound to the `id` attribute of the `<input>` element.

**Comment by kampsy** [comment]
Feature added and tested

https://github.com/user-attachments/assets/059fd139-338f-4df1-947a-c3f59ace1467
