### ISSUE TITLE
Fix installation docs to use new cli

### ISSUE THREAD

**Issue by cliffordkleinsr** [kampsy/ui#22]
Svelte 5 has released. Can migrate the docs to use new cli. Also add bun yarn amd npm  commands for installing. Shouldn't ve too hard ;)

**Comment by anzhi0708** [comment]
Seems like tailwind config needs update too (`kampsyUI` -> `kampsyui`) :-)

**Comment by kampsy** [comment]
Migrating the documentation to the new Svelte CLI is a great idea—making the Tailwind setup much smoother! I will also include installation instructions for Bun, Yarn, and NPM to make the setup as straightforward as possible. Thank you for the suggestion. It shouldn't be too difficult and will streamline everyone's experience. 😊
