### ISSUE TITLE
Remove `capitalize` class from Badge

### ISSUE THREAD

**Issue by WaldvogelMGB** [kampsy/ui#27]
Not all languages use capitalization for emphasis. For example, indiscriminate capitalization of sentences looks very confusing to German readers (and probably several others).

I therefore suggest one of the following changes to `Badge`, in increasing complexity:

1. Entirely remove `capitalize`
2. Make `capitalize` optional using a prop
3. Add a `text-decoration` property, which can specify additional classes to the inner `span` (after removing `capitalize`)

https://github.com/kampsy/ui/blob/cee42c40ba297edbe535746f61222d26dd196bff/src/lib/badge/badge.svelte#L116

**Comment by WaldvogelMGB** [comment]
Alternative (preferred, after some thought):

4. Remove `capitalize` from the `span` and let the user specify `capitalize` as an option to `<Badge class='capitalize'>`, if desired, to be inherited by the `span`

**Comment by kampsy** [comment]
I also prefer the 4th option. It is better to remove capitalization from the span and allow users to specify capitalization as an option to `<Badge class='capitalize'>` I will fix this issue in the next PR.
Thank you for your contribution

**Comment by WaldvogelMGB** [comment]
Wow, that was fast! Thanks!

In the meantime (while using the source code as extra documentation), I found that there are other `capitalize` and `first-letter:capitalize` statements in the source. Haven't looked into them in detail, but they could be candidates for "number 4 treatment" as well.
